// <auto-generated />
using System;
using System.Collections.Generic;
using Kadans.Modules.Tasks.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kadans.Modules.Tasks.Persistence.Migrations
{
    [DbContext(typeof(TasksDbContext))]
    [Migration("20260830142306_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tasks")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentPhaseIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_phase_index");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<Guid?>("PomodoroTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("pomodoro_template_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pomodoro_runs");

                    b.HasIndex("TodoId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_pomodoro_runs_todo_id_started_at_desc");

                    b.HasIndex("UserId", "Status", "StartedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_pomodoro_runs_user_id_status_started_at_desc");

                    b.ToTable("pomodoro_runs", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroRunPhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PomodoroRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("pomodoro_run_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pomodoro_run_phases");

                    b.HasIndex("PomodoroRunId", "Order")
                        .HasDatabaseName("ix_pomodoro_run_phases_run_order");

                    b.ToTable("pomodoro_run_phases", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pomodoro_templates");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_pomodoro_templates_user_id_created_at_desc");

                    b.ToTable("pomodoro_templates", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroTemplatePhase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PomodoroTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("pomodoro_template_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_pomodoro_template_phases");

                    b.HasIndex("PomodoroTemplateId", "Order")
                        .HasDatabaseName("ix_pomodoro_template_phases_template_order");

                    b.ToTable("pomodoro_template_phases", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<DateTimeOffset>>("Exceptions")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("exceptions");

                    b.Property<string>("Rrule")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("rrule");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_recurrence_rules");

                    b.ToTable("recurrence_rules", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_enabled");

                    b.Property<TimeSpan>("NotificationLeadTime")
                        .HasColumnType("interval")
                        .HasColumnName("notification_lead_time");

                    b.Property<Guid?>("PomodoroTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("pomodoro_template_id");

                    b.Property<Guid>("RecurrenceRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurrence_rule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.HasIndex("PomodoroTemplateId");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_todos_user_id_created_at_desc");

                    b.HasIndex("UserId", "Id")
                        .HasDatabaseName("ix_todos_user_id_id");

                    b.HasIndex("UserId", "CreatedAt", "Id")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("ix_todos_user_id_created_at_id_active")
                        .HasFilter("status IN ('Scheduled', 'Started')");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_todos_user_id_status_created_at_desc");

                    b.ToTable("todos", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.TodoOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsRescheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rescheduled");

                    b.Property<DateTimeOffset>("OccurrenceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_date");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_occurrences");

                    b.HasIndex("OccurrenceDate")
                        .HasDatabaseName("ix_todo_occurrences_occurrence_date_active")
                        .HasFilter("NOT is_cancelled AND NOT is_completed");

                    b.HasIndex("TodoId", "OccurrenceDate")
                        .HasDatabaseName("ix_todo_occurrences_todo_id_occurrence_date");

                    b.ToTable("todo_occurrences", "tasks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroRun", b =>
                {
                    b.HasOne("Kadans.Modules.Tasks.Domain.Todo", "Todo")
                        .WithMany()
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pomodoro_runs_todos_todo_id");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroRunPhase", b =>
                {
                    b.HasOne("Kadans.Modules.Tasks.Domain.PomodoroRun", null)
                        .WithMany("Phases")
                        .HasForeignKey("PomodoroRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pomodoro_run_phases_pomodoro_runs_pomodoro_run_id");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroTemplatePhase", b =>
                {
                    b.HasOne("Kadans.Modules.Tasks.Domain.PomodoroTemplate", null)
                        .WithMany("Phases")
                        .HasForeignKey("PomodoroTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pomodoro_template_phases_pomodoro_templates_pomodoro_templa~");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.Todo", b =>
                {
                    b.HasOne("Kadans.Modules.Tasks.Domain.PomodoroTemplate", "PomodoroTemplate")
                        .WithMany()
                        .HasForeignKey("PomodoroTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_todos_pomodoro_templates_pomodoro_template_id");

                    b.HasOne("Kadans.Modules.Tasks.Domain.RecurrenceRule", "RecurrenceRule")
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todos_recurrence_rules_recurrence_rule_id");

                    b.OwnsMany("Kadans.Modules.Tasks.Domain.TodoRemark", "Remarks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Remark")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("remark");

                            b1.Property<Guid>("TodoId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id");

                            b1.HasIndex("TodoId");

                            b1.ToTable("todo_remarks", "tasks");

                            b1.WithOwner()
                                .HasForeignKey("TodoId")
                                .HasConstraintName("fk_todo_remark_todos_todo_id");
                        });

                    b.Navigation("PomodoroTemplate");

                    b.Navigation("RecurrenceRule");

                    b.Navigation("Remarks");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.TodoOccurrence", b =>
                {
                    b.HasOne("Kadans.Modules.Tasks.Domain.Todo", "Todo")
                        .WithMany()
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_occurrences_todos_todo_id");

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroRun", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Kadans.Modules.Tasks.Domain.PomodoroTemplate", b =>
                {
                    b.Navigation("Phases");
                });
#pragma warning restore 612, 618
        }
    }
}
