<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Kadans.Api/Kadans.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

</Project>
