import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinxSerialization)
}

// The server a build talks to by default. Unset (every dev build): the per-platform localhost
// defaults. A release build passes the public API:
//   ./gradlew :androidApp:assembleRelease -Pkadans.apiBaseUrl=https://api.kadans.app
// (or put kadans.apiBaseUrl=… in ~/.gradle/gradle.properties on the release machine).
val kadansApiBaseUrl: String = providers.gradleProperty("kadans.apiBaseUrl").orNull?.trim()?.trimEnd('/').orEmpty()
val generateKadansBuildConfig by tasks.registering {
    val url = kadansApiBaseUrl
    val outputDir = layout.buildDirectory.dir("generated/kadans/commonMain/kotlin")
    inputs.property("apiBaseUrl", url)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("app/kadans/config/BuildConfig.kt").asFile
        file.parentFile.mkdirs()
        val literal = if (url.isEmpty()) "null" else "\"" + url.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$") + "\""
        file.writeText(
            "package app.kadans.config\n\n" +
                "/** Generated by :shared:generateKadansBuildConfig from -Pkadans.apiBaseUrl. Do not edit. */\n" +
                "internal object BuildConfig {\n    val API_BASE_URL: String? = " + literal + "\n}\n"
        )
    }
}

kotlin {
    jvm()

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    androidLibrary {
        namespace = "app.kadans.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
        androidResources {
            enable = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateKadansBuildConfig) // the task is wired as the producer of this directory
        }
        all {
            languageSettings.optIn("kotlin.time.ExperimentalTime")
            languageSettings.optIn("kotlin.uuid.ExperimentalUuidApi")
            languageSettings.optIn("androidx.compose.material3.ExperimentalMaterial3Api")
            languageSettings.optIn("androidx.compose.foundation.layout.ExperimentalLayoutApi")
        }

        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.firebase.messaging)
            // Google sign-in through Credential Manager (play-services-auth backs it below Android 14)
            implementation(libs.androidx.credentials)
            implementation(libs.androidx.credentials.playServicesAuth)
            implementation(libs.googleid)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        jvmMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.kotlinx.coroutines.swing)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)

            implementation(libs.navigation3.runtime)
            implementation(libs.navigation3.ui)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.viewmodelNavigation3)

            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)

            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.auth)
            implementation(libs.ktor.client.websockets)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)

            implementation(libs.koin.core)
            implementation(libs.koin.compose.viewmodel)

            implementation(libs.multiplatform.settings)
            implementation(libs.multiplatform.settings.noarg)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.ktor.client.mock)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}
