// <auto-generated />
using System;
using System.Collections.Generic;
using Kadans.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kadans.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260206000551_TodoOccurrenceState")]
    partial class TodoOccurrenceState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<int[]>("ByDay")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_day");

                    b.PrimitiveCollection<List<int>>("ByHour")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_hour");

                    b.PrimitiveCollection<List<int>>("ByMinute")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_minute");

                    b.PrimitiveCollection<List<int>>("ByMonth")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_month");

                    b.PrimitiveCollection<List<int>>("ByMonthDay")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_month_day");

                    b.PrimitiveCollection<List<int>>("BySetPos")
                        .HasColumnType("integer[]")
                        .HasColumnName("by_set_pos");

                    b.Property<int?>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.PrimitiveCollection<List<DateTimeOffset>>("Exceptions")
                        .HasColumnType("timestamp with time zone[]")
                        .HasColumnName("exceptions");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset?>("Until")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("until");

                    b.HasKey("Id")
                        .HasName("pk_recurrence_rules");

                    b.ToTable("recurrence_rules");
                });

            modelBuilder.Entity("Api.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("NotificationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_enabled");

                    b.Property<Guid>("RecurrenceRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurrence_rule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_todos");

                    b.HasIndex("RecurrenceRuleId");

                    b.ToTable("todos");
                });

            modelBuilder.Entity("Api.Models.TodoOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cancelled");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsRescheduled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rescheduled");

                    b.Property<DateTimeOffset>("OccurrenceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_date");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("todo_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_occurrences");

                    b.HasIndex("TodoId");

                    b.ToTable("todo_occurrences");
                });

            modelBuilder.Entity("Api.Models.Todo", b =>
                {
                    b.HasOne("Api.Models.RecurrenceRule", "RecurrenceRule")
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todos_recurrence_rules_recurrence_rule_id");

                    b.OwnsMany("Api.Models.TodoRemark", "Remarks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Remark")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("remark");

                            b1.Property<Guid>("TodoId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id");

                            b1.HasIndex("TodoId");

                            b1.ToTable("todo_remarks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TodoId")
                                .HasConstraintName("fk_todo_remark_todos_todo_id");
                        });

                    b.Navigation("RecurrenceRule");

                    b.Navigation("Remarks");
                });

            modelBuilder.Entity("Api.Models.TodoOccurrence", b =>
                {
                    b.HasOne("Api.Models.Todo", "Todo")
                        .WithMany()
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_occurrences_todos_todo_id");

                    b.Navigation("Todo");
                });
#pragma warning restore 612, 618
        }
    }
}
