<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Kadans.Modules.Budget/Kadans.Modules.Budget.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

</Project>
